[tox]
envlist = py310, py311, py312, py313, py314, pypy3, coverage, pre-commit, docs, perf
skipsdist = True
skip_missing_interpreters = True

[testenv]
usedevelop = True
extras = test
commands = pytest {posargs}

[testenv:coverage]
basepython = python
extras = test
         coverage

commands = pytest --cov --cov-fail-under=100 {posargs}

[testenv:pre-commit]
deps = pre-commit
commands = pre-commit run --all-files

[testenv:docs]
basepython = python3
extras = docs

commands = sphinx-build -b doctest doc {envtmpdir}

[testenv:perf]
basepython = python3
extras =

commands = python {toxinidir}/tox_perf.py

[gh-actions]
python =
    3.10: py310, perf
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314, pre-commit, coverage
    pypy-3.10: pypy3

[flake8]
max-line-length = 88
ignore =
    E231  # clashes with black
    W503
    E731  # todo
